// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjrwPRX132Z_zFt7J1pSvZKMv7FGKzbRw',
    appId: '1:129823554244:web:1984828dbbb088f9c16791',
    messagingSenderId: '129823554244',
    projectId: 'kelompok2-5b5f7',
    authDomain: 'kelompok2-5b5f7.firebaseapp.com',
    storageBucket: 'kelompok2-5b5f7.firebasestorage.app',
    measurementId: 'G-7ZXZNN0J8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuwDTIgu8o1yuzSi_vnikOeXGxZONTa2M',
    appId: '1:129823554244:android:ca6433f65fcb56c1c16791',
    messagingSenderId: '129823554244',
    projectId: 'kelompok2-5b5f7',
    storageBucket: 'kelompok2-5b5f7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjrwPRX132Z_zFt7J1pSvZKMv7FGKzbRw',
    appId: '1:129823554244:web:06ee1b097d17f219c16791',
    messagingSenderId: '129823554244',
    projectId: 'kelompok2-5b5f7',
    authDomain: 'kelompok2-5b5f7.firebaseapp.com',
    storageBucket: 'kelompok2-5b5f7.firebasestorage.app',
    measurementId: 'G-NWZMZXWJHH',
  );

}